name: Mapify
version: '${project.version}'
main: com.funnyboyroks.mapify.Mapify
api-version: 1.19
authors: [ funnyboy_roks ]
description: A plugin to convert your images into maps!
commands:
  mapify:
    usage: /mapify <url> [dimensions]
    description: Create a map or maps from a url
    permission: mapify.command.mapify
  refreshmaps:
    usage: /refreshmaps
    description: Rerender all maps in your inventory
    permission: mapify.command.refreshmaps
permissions:
  mapify.command.mapify:
    default: op
    description: Permission to use the command `/mapify`
  mapify.command.refreshmaps:
    default: op
    description: Permission to use the command `/refreshmaps`
